//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbPhoneStoreEntities : DbContext
    {
        public dbPhoneStoreEntities()
            : base("name=dbPhoneStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_ChucVu> tb_ChucVu { get; set; }
        public virtual DbSet<tb_CTHDBanHang> tb_CTHDBanHang { get; set; }
        public virtual DbSet<tb_CTHDNhapHang> tb_CTHDNhapHang { get; set; }
        public virtual DbSet<tb_DanhMuc> tb_DanhMuc { get; set; }
        public virtual DbSet<tb_HDBanHang> tb_HDBanHang { get; set; }
        public virtual DbSet<tb_HDNhapHang> tb_HDNhapHang { get; set; }
        public virtual DbSet<tb_KhachHang> tb_KhachHang { get; set; }
        public virtual DbSet<tb_NCC_ThgHieu> tb_NCC_ThgHieu { get; set; }
        public virtual DbSet<tb_NhaCungCap> tb_NhaCungCap { get; set; }
        public virtual DbSet<tb_NhanVien> tb_NhanVien { get; set; }
        public virtual DbSet<tb_SanPham> tb_SanPham { get; set; }
        public virtual DbSet<tb_ThuongHieu> tb_ThuongHieu { get; set; }
        public virtual DbSet<tb_TrangThaiHoaDon> tb_TrangThaiHoaDon { get; set; }
        public virtual DbSet<tb_TrangThaiSanPham> tb_TrangThaiSanPham { get; set; }
    
        [DbFunction("dbPhoneStoreEntities", "ChiTietDonHang")]
        public virtual IQueryable<ChiTietDonHang_Result> ChiTietDonHang(Nullable<int> maHDBH)
        {
            var maHDBHParameter = maHDBH.HasValue ?
                new ObjectParameter("MaHDBH", maHDBH) :
                new ObjectParameter("MaHDBH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ChiTietDonHang_Result>("[dbPhoneStoreEntities].[ChiTietDonHang](@MaHDBH)", maHDBHParameter);
        }
    
        [DbFunction("dbPhoneStoreEntities", "SanPham")]
        public virtual IQueryable<SanPham_Result> SanPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SanPham_Result>("[dbPhoneStoreEntities].[SanPham]()");
        }
    
        [DbFunction("dbPhoneStoreEntities", "TimKiemSanPham")]
        public virtual IQueryable<TimKiemSanPham_Result> TimKiemSanPham(string query)
        {
            var queryParameter = query != null ?
                new ObjectParameter("query", query) :
                new ObjectParameter("query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TimKiemSanPham_Result>("[dbPhoneStoreEntities].[TimKiemSanPham](@query)", queryParameter);
        }
    
        [DbFunction("dbPhoneStoreEntities", "top10SP")]
        public virtual IQueryable<top10SP_Result> top10SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<top10SP_Result>("[dbPhoneStoreEntities].[top10SP]()");
        }
    
        public virtual ObjectResult<DonHang_Result> DonHang(string sDT)
        {
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DonHang_Result>("DonHang", sDTParameter);
        }
    
        public virtual int DuyetDonHang(Nullable<int> id, Nullable<int> maNV)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DuyetDonHang", idParameter, maNVParameter);
        }
    
        public virtual ObjectResult<LayTatCaDonHang_Result> LayTatCaDonHang(Nullable<int> id_trangthai)
        {
            var id_trangthaiParameter = id_trangthai.HasValue ?
                new ObjectParameter("id_trangthai", id_trangthai) :
                new ObjectParameter("id_trangthai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayTatCaDonHang_Result>("LayTatCaDonHang", id_trangthaiParameter);
        }
    
        public virtual ObjectResult<LoginPhoneStore_Result> LoginPhoneStore(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginPhoneStore_Result>("LoginPhoneStore", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<ThongKeDoanhThu_Result> ThongKeDoanhThu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeDoanhThu_Result>("ThongKeDoanhThu");
        }
    
        public virtual ObjectResult<ThongKeKhachHang_Result> ThongKeKhachHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeKhachHang_Result>("ThongKeKhachHang");
        }
    
        public virtual ObjectResult<ThongKeNhanVien_Result> ThongKeNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeNhanVien_Result>("ThongKeNhanVien");
        }
    
        public virtual ObjectResult<ThongKeNhanVienDonHang_Result> ThongKeNhanVienDonHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeNhanVienDonHang_Result>("ThongKeNhanVienDonHang");
        }
    
        public virtual ObjectResult<ThongKeThuongHieuSaPham_Result> ThongKeThuongHieuSaPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeThuongHieuSaPham_Result>("ThongKeThuongHieuSaPham");
        }
    
        public virtual ObjectResult<ThongKeTop10SanPham_Result> ThongKeTop10SanPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeTop10SanPham_Result>("ThongKeTop10SanPham");
        }
    
        public virtual ObjectResult<TimKiemDonHang_Result> TimKiemDonHang(string sDT)
        {
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiemDonHang_Result>("TimKiemDonHang", sDTParameter);
        }
    }
}
