//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CTHDNhapHang
    {
        public int ID_CTHDNH { get; set; }
        public int MaHDNH { get; set; }
        public int MaSP { get; set; }
        public decimal GiaNhap { get; set; }
        public int SoLuong { get; set; }
    
        public virtual tb_HDNhapHang tb_HDNhapHang { get; set; }
        public virtual tb_SanPham tb_SanPham { get; set; }
    }
}
