//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HDNhapHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_HDNhapHang()
        {
            this.tb_CTHDNhapHang = new HashSet<tb_CTHDNhapHang>();
        }
    
        public int MaHDNH { get; set; }
        public int MaNV { get; set; }
        public System.DateTime NgayLap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CTHDNhapHang> tb_CTHDNhapHang { get; set; }
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
