//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HDBanHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_HDBanHang()
        {
            this.tb_CTHDBanHang = new HashSet<tb_CTHDBanHang>();
        }
    
        public int MaHDBH { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public int TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CTHDBanHang> tb_CTHDBanHang { get; set; }
        public virtual tb_KhachHang tb_KhachHang { get; set; }
        public virtual tb_NhanVien tb_NhanVien { get; set; }
        public virtual tb_TrangThaiHoaDon tb_TrangThaiHoaDon { get; set; }
    }
}
