//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NCC_ThgHieu
    {
        public int MaNCC { get; set; }
        public int MaThgHieu { get; set; }
        public int ID { get; set; }
    
        public virtual tb_ThuongHieu tb_ThuongHieu { get; set; }
        public virtual tb_NhaCungCap tb_NhaCungCap { get; set; }
    }
}
